sites = [
    ['Google', 'https://google.com/'],
    ['Amazon', 'https://amazon.com/'],
    ['YouTube', 'https://youtube.com/'],
    ['Facebook', 'https://facebook.com/'],
    ['Wikipedia', 'https://wikipedia.org/'],
    ['Twitter', 'https://twitter.com/'],
    ['LinkedIn', 'https://linkedin.com/'],
    ['Instagram', 'https://instagram.com/'],
    ['Pinterest', 'https://pinterest.com/'],
    ['Reddit', 'https://reddit.com/'],
    ['GitHub', 'https://github.com/'],
    ['Stack Overflow', 'https://stackoverflow.com/'],
    ['Medium', 'https://medium.com/'],
    ['Quora', 'https://quora.com/'],
    ['Netflix', 'https://netflix.com/'],
    ['Hulu', 'https://hulu.com/'],
    ['Apple', 'https://apple.com/'],
    ['Microsoft', 'https://microsoft.com/'],
    ['CNN', 'https://cnn.com/'],
    ['BBC', 'https://bbc.com/'],
    ['The New York Times', 'https://nytimes.com/'],
    ['The Guardian', 'https://theguardian.com/'],
    ['TechCrunch', 'https://techcrunch.com/'],
    ['Wired', 'https://wired.com/'],
    ['National Geographic', 'https://www.nationalgeographic.com/'],
    ['NASA', 'https://www.nasa.gov/'],
    ['IMDb', 'https://www.imdb.com/'],
    ['Etsy', 'https://www.etsy.com/'],
    ['Walmart', 'https://www.walmart.com/'],
    ['Target', 'https://www.target.com/'],
    ['Best Buy', 'https://www.bestbuy.com/'],
    ['BBC News', 'https://www.bbc.co.uk/news'],
    ['Forbes', 'https://www.forbes.com/'],
    ['The Wall Street Journal', 'https://www.wsj.com/'],
    ['Reuters', 'https://www.reuters.com/'],
    ['The Verge', 'https://www.theverge.com/'],
    ['CNET', 'https://www.cnet.com/'],
    ['TED', 'https://www.ted.com/'],
    ['WebMD', 'https://www.webmd.com/'],
    ['Mayo Clinic', 'https://www.mayoclinic.org/'],
    ['Merriam-Webster', 'https://www.merriam-webster.com/'],
    ['Urban Dictionary', 'https://www.urbandictionary.com/'],
    ['Britannica', 'https://www.britannica.com/'],
    ['Dictionary.com', 'https://www.dictionary.com/'],
    ['Worldometer', 'https://www.worldometers.info/'],
    ['Google News', 'https://news.google.com/'],
    ['Al Jazeera', 'https://www.aljazeera.com/'],
    ['NBC News', 'https://www.nbcnews.com/'],
    ['CBS News', 'https://www.cbsnews.com/'],
    ['ABC News', 'https://abcnews.go.com/'],
    ['Fox News', 'https://www.foxnews.com/'],
    ['USA Today', 'https://www.usatoday.com/'],
    ['Time', 'https://time.com/'],
    ['The Washington Post', 'https://www.washingtonpost.com/'],
    ['The Economist', 'https://www.economist.com/'],
    ['Bloomberg', 'https://www.bloomberg.com/'],
    ['CNBC', 'https://www.cnbc.com/'],
    ['Investopedia', 'https://www.investopedia.com/'],
    ['The New Yorker', 'https://www.newyorker.com/'],
    ['Harvard University', 'https://www.harvard.edu/'],
    ['Stanford University', 'https://www.stanford.edu/'],
    ['MIT', 'https://www.mit.edu/'],
    ['University of Oxford', 'https://www.ox.ac.uk/'],
    ['University of Cambridge', 'https://www.cam.ac.uk/'],
    ['Caltech', 'https://www.caltech.edu/'],
    ['Yale University', 'https://www.yale.edu/'],
    ['University of Chicago', 'https://www.uchicago.edu/'],
    ['University of California, Berkeley', 'https://www.berkeley.edu/'],
    ['World Health Organization', 'https://www.who.int/'],
    ['Centers for Disease Control and Prevention (CDC)', 'https://www.cdc.gov/'],
    ['European Space Agency', 'https://www.esa.int/'],
    ['United Nations', 'https://www.un.org/'],
    ['World Bank', 'https://www.worldbank.org/'],
    ['Food and Agriculture Organization (FAO)', 'http://www.fao.org/'],
    ['Environmental Protection Agency (EPA)', 'https://www.epa.gov/'],
    ['American Red Cross', 'https://www.redcross.org/'],
    ['UNICEF', 'https://www.unicef.org/'],
    ['Amnesty International', 'https://www.amnesty.org/'],
    ['Greenpeace', 'https://www.greenpeace.org/'],
    ['World Wildlife Fund (WWF)', 'https://www.worldwildlife.org/'],
    ['Make-A-Wish Foundation', 'https://wish.org/'],
    ['Doctors Without Borders', 'https://www.doctorswithoutborders.org/'],
    ['Human Rights Watch', 'https://www.hrw.org/'],
    ['The Nature Conservancy', 'https://www.nature.org/'],
    ['American Cancer Society', 'https://www.cancer.org/'],
    ['American Heart Association', 'https://www.heart.org/'],
    ['Alzheimer\'s Association', 'https://www.alz.org/'],
    ['Autism Speaks', 'https://www.autismspeaks.org/'],
    ['National Alliance on Mental Illness (NAMI)', 'https://www.nami.org/'],
    ['American Diabetes Association', 'https://www.diabetes.org/'],
    ['Samaritans', 'https://www.samaritans.org/'],
    ['National Suicide Prevention Lifeline', 'https://suicidepreventionlifeline.org/'],
    ['Crisis Text Line', 'https://www.crisistextline.org/'],
    ['National Domestic Violence Hotline', 'https://www.thehotline.org/'],
    ['National Runaway Safeline', 'https://www.1800runaway.org/'],
    ['Narcotics Anonymous', 'https://www.na.org/'],
    ['Alcoholics Anonymous', 'https://www.aa.org/'],
    ['National Sexual Assault Hotline', 'https://www.rainn.org/'],
    ['National Eating Disorders Association (NEDA)', 'https://www.nationaleatingdisorders.org/'],
    ['Gamblers Anonymous', 'https://www.gamblersanonymous.org/'],
    ['Quit Smoking Community', 'https://quitsmokingcommunity.org/']]